version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/shoesbox-vanilla
    overwrite: yes

permissions:
  - object: /usr/share/nginx/html/shoesbox-vanilla
    owner: root
    group: root
    mode: 755

hooks:
  AfterInstall:
    - location: after-deploy.sh
      timeout: 180
      runas: root
