  version: 0.0
  os: linux
  
  files:
    - source: /
      destination: /home/ubuntu/build
      overwrite: yes
      
  permissions:
    - object: /home/ubuntu/build
      owner: ubuntu
      group: ubuntu
      mode: 755
      
