version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/shoesbox-vanilla
    overwrite: yes

permissions:
  - object: /home/ubuntu/shoesbox-vanilla
    pattern: '**'
    owner: ubuntu
    group: ubuntu
    mode: 775

hooks:
  AfterInstall:
    - location: after-deploy.sh
      timeout: 180
      runas: ubuntu
