version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build
    overwrite: yes

permissions:
  - object: /home/ec2-user/build
    owner: linux
    group: linux
    mode: 755

hooks:
  BeforeInstall:
    - location: before-deploy.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: after-deploy.sh
      timeout: 180
      runas: root
